apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: golddb
    user: gold
    secureJsonData:
      password: gold
    jsonData:
      sslmode: disable
      postgresVersion: 1500

  - name: Dragonfly
    type: redis-datasource
    url: dragonfly:6379
    jsonData:
      client: generic
      poolSize: 5
      timeout: 10
      pingInterval: 0
      dataSourceInfo:
        - name: Streams
          type: streams
